export const symptoms = [
    { id: 0, name: 'itching' },
    { id: 1, name: 'skin rash' },
    { id: 2, name: 'skin eruptions' },
    { id: 3, name: 'continuous sneezing' },
    { id: 4, name: 'shivering' },
    { id: 5, name: 'chills' },
    { id: 6, name: 'joint pain' },
    { id: 7, name: 'stomach pain' },
    { id: 8, name: 'acidity' },
    { id: 9, name: 'tongue ulcers' },
    { id: 10, name: 'muscle atrophy' },
    { id: 11, name: 'vomiting' },
    { id: 12, name: 'burning micturition' },
    { id: 13, name: 'spotting urination' },
    { id: 14, name: 'fatigue' },
    { id: 15, name: 'weight gain' },
    { id: 16, name: 'anxiety' },
    { id: 17, name: 'cold hands and feet' },
    { id: 18, name: 'mood swings' },
    { id: 19, name: 'weight loss' },
    { id: 20, name: 'restlessness' },
    { id: 21, name: 'lethargy' },
    { id: 22, name: 'throat patches' },
    { id: 23, name: 'irregular sugar level' },
    { id: 24, name: 'cough' },
    { id: 25, name: 'high fever' },
    { id: 26, name: 'sunken eyes' },
    { id: 27, name: 'breathlessness' },
    { id: 28, name: 'sweating' },
    { id: 29, name: 'dehydration' },
    { id: 30, name: 'indigestion' },
    { id: 31, name: 'headache' },
    { id: 32, name: 'yellowish skin' },
    { id: 33, name: 'dark urine' },
    { id: 34, name: 'nausea' },
    { id: 35, name: 'loss of appetite' },
    { id: 36, name: 'eye pain' },
    { id: 37, name: 'back pain' },
    { id: 38, name: 'constipation' },
    { id: 39, name: 'abdominal pain ' },
    { id: 40, name: 'diarrhoea' },
    { id: 41, name: 'mild fever' },
    { id: 42, name: 'yellow urine' },
    { id: 43, name: 'yellowing of eyes' },
    { id: 44, name: 'acute liver failure' },
    { id: 45, name: 'fluid overload' },
    { id: 46, name: 'stomach swelling' },
    { id: 47, name: 'swollen lymph nodes' },
    { id: 48, name: 'malaise' },
    { id: 49, name: 'blurred vision' },
    { id: 50, name: 'phlegm' },
    { id: 51, name: 'throat irritation' },
    { id: 52, name: 'redness of eyes' },
    { id: 53, name: 'sinus pressure' },
    { id: 54, name: 'runny nose' },
    { id: 55, name: 'congestion' },
    { id: 56, name: 'chest pain' },
    { id: 57, name: 'limb weakness' },
    { id: 58, name: 'fast heart rate' },
    { id: 59, name: 'bowel movement pain' },
    { id: 61, name: 'anal region pain' },
    { id: 62, name: 'bloody stool' },
    { id: 63, name: 'anus irritation' },
    { id: 64, name: 'neck pain' },
    { id: 65, name: 'dizziness' },
    { id: 66, name: 'cramps' },
    { id: 67, name: 'bruising' },
    { id: 68, name: 'obesity' },
    { id: 69, name: 'swollen legs' },
    { id: 70, name: 'swollen blood vessels' },
    { id: 71, name: 'puffy face and eyes' },
    { id: 72, name: 'enlarged thyroid' },
    { id: 73, name: 'brittle_nails' },
    { id: 74, name: 'swollen extremeties' },
    { id: 75, name: 'excessive hunger' },
    { id: 76, name: 'extra marital contacts' },
    { id: 77, name: 'drying lips' },
    { id: 78, name: 'slurred speech' },
    { id: 79, name: 'knee pain' },
    { id: 80, name: 'hip joint pain' },
    { id: 81, name: 'muscle weakness' },
    { id: 82, name: 'stiff neck' },
    { id: 83, name: 'swelling joints' },
    { id: 84, name: 'movement stiffness' },
    { id: 85, name: 'spinning movements' },
    { id: 86, name: 'loss of balance' },
    { id: 87, name: 'unsteadiness' },
    { id: 88, name: 'one body side weakness' },
    { id: 89, name: 'loss of smell' },
    { id: 90, name: 'bladder discomfort' },
    { id: 91, name: 'foul smell of urine' },
    { id: 92, name: 'continuous feel of urine' },
    { id: 93, name: 'passage of gases' },
    { id: 94, name: 'internal_itching' },
    { id: 95, name: 'toxic look (typhos)' },
    { id: 96, name: 'depression' },
    { id: 97, name: 'irritability' },
    { id: 98, name: 'muscle pain' },
    { id: 99, name: 'altered sensorium' },
    { id: 100, name: 'red spots' },
    { id: 101, name: 'belly pain' },
    { id: 102, name: 'abnormal menstrution' },
    { id: 103, name: 'dischromic patches' },
    { id: 104, name: 'watery eyes' },
    { id: 105, name: 'increased appetite' },
    { id: 106, name: 'polyuria' },
    { id: 107, name: 'family_history' },
    { id: 108, name: 'mucoid sputum' },
    { id: 109, name: 'rusty sputum' },
    { id: 110, name: 'lack of concentration' },
    { id: 111, name: 'visual disturbance' },
    { id: 112, name: 'receiving blood transfusion' },
    { id: 113, name: 'receiving unsterile injections' },
    { id: 114, name: 'coma' },
    { id: 115, name: 'stomach bleeding' },
    { id: 116, name: 'distention of abdomen' },
    { id: 117, name: 'history of alcohol consumption' },
    { id: 118, name: 'fluid overload' },
    { id: 119, name: 'blood in sputum' },
    { id: 120, name: 'prominent veins on calfs' },
    { id: 121, name: 'palpitations' },
    { id: 122, name: 'painful walking' },
    { id: 123, name: 'pus filled pimples' },
    { id: 124, name: 'blackheads' },
    { id: 125, name: 'scurring' },
    { id: 126, name: 'skin peeling' },
    { id: 127, name: 'silver like dusting' },
    { id: 128, name: 'dents in nails' },
    { id: 129, name: 'inflammatory nails' },
    { id: 130, name: 'blister' },
    { id: 131, name: 'soreness around nose' },
    { id: 132, name: 'yellow crust ooze' }
]